version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: ./dockerization/Dockerfile
    restart: always
    ports:
      - "80:5000"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/byod_voting
      - SESSION_SECRET=${SESSION_SECRET}
    networks:
      - byod-network

  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=byod_voting
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - byod-network

networks:
  byod-network:
    driver: bridge

volumes:
  postgres-data: